-- One logical DB per microservice (polyrepo-friendly).
CREATE USER erp WITH PASSWORD 'erp';

CREATE DATABASE auth OWNER erp;
CREATE DATABASE hr OWNER erp;
CREATE DATABASE procurement OWNER erp;
CREATE DATABASE warehouse OWNER erp;
CREATE DATABASE finance OWNER erp;

GRANT ALL PRIVILEGES ON DATABASE auth TO erp;
GRANT ALL PRIVILEGES ON DATABASE hr TO erp;
GRANT ALL PRIVILEGES ON DATABASE procurement TO erp;
GRANT ALL PRIVILEGES ON DATABASE warehouse TO erp;
GRANT ALL PRIVILEGES ON DATABASE finance TO erp;
