// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: erp/procurement/v1/procurement.proto

package procurementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcurementService_CreateSupplier_FullMethodName      = "/erp.procurement.v1.ProcurementService/CreateSupplier"
	ProcurementService_ListSuppliers_FullMethodName       = "/erp.procurement.v1.ProcurementService/ListSuppliers"
	ProcurementService_CreatePurchaseOrder_FullMethodName = "/erp.procurement.v1.ProcurementService/CreatePurchaseOrder"
	ProcurementService_GetPurchaseOrder_FullMethodName    = "/erp.procurement.v1.ProcurementService/GetPurchaseOrder"
	ProcurementService_ListPurchaseOrders_FullMethodName  = "/erp.procurement.v1.ProcurementService/ListPurchaseOrders"
)

// ProcurementServiceClient is the client API for ProcurementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcurementServiceClient interface {
	CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*Supplier, error)
	ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error)
	CreatePurchaseOrder(ctx context.Context, in *CreatePurchaseOrderRequest, opts ...grpc.CallOption) (*PurchaseOrder, error)
	GetPurchaseOrder(ctx context.Context, in *GetPurchaseOrderRequest, opts ...grpc.CallOption) (*PurchaseOrder, error)
	ListPurchaseOrders(ctx context.Context, in *ListPurchaseOrdersRequest, opts ...grpc.CallOption) (*ListPurchaseOrdersResponse, error)
}

type procurementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcurementServiceClient(cc grpc.ClientConnInterface) ProcurementServiceClient {
	return &procurementServiceClient{cc}
}

func (c *procurementServiceClient) CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*Supplier, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Supplier)
	err := c.cc.Invoke(ctx, ProcurementService_CreateSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procurementServiceClient) ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSuppliersResponse)
	err := c.cc.Invoke(ctx, ProcurementService_ListSuppliers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procurementServiceClient) CreatePurchaseOrder(ctx context.Context, in *CreatePurchaseOrderRequest, opts ...grpc.CallOption) (*PurchaseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseOrder)
	err := c.cc.Invoke(ctx, ProcurementService_CreatePurchaseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procurementServiceClient) GetPurchaseOrder(ctx context.Context, in *GetPurchaseOrderRequest, opts ...grpc.CallOption) (*PurchaseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseOrder)
	err := c.cc.Invoke(ctx, ProcurementService_GetPurchaseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *procurementServiceClient) ListPurchaseOrders(ctx context.Context, in *ListPurchaseOrdersRequest, opts ...grpc.CallOption) (*ListPurchaseOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPurchaseOrdersResponse)
	err := c.cc.Invoke(ctx, ProcurementService_ListPurchaseOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcurementServiceServer is the server API for ProcurementService service.
// All implementations must embed UnimplementedProcurementServiceServer
// for forward compatibility.
type ProcurementServiceServer interface {
	CreateSupplier(context.Context, *CreateSupplierRequest) (*Supplier, error)
	ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error)
	CreatePurchaseOrder(context.Context, *CreatePurchaseOrderRequest) (*PurchaseOrder, error)
	GetPurchaseOrder(context.Context, *GetPurchaseOrderRequest) (*PurchaseOrder, error)
	ListPurchaseOrders(context.Context, *ListPurchaseOrdersRequest) (*ListPurchaseOrdersResponse, error)
	mustEmbedUnimplementedProcurementServiceServer()
}

// UnimplementedProcurementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcurementServiceServer struct{}

func (UnimplementedProcurementServiceServer) CreateSupplier(context.Context, *CreateSupplierRequest) (*Supplier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupplier not implemented")
}
func (UnimplementedProcurementServiceServer) ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSuppliers not implemented")
}
func (UnimplementedProcurementServiceServer) CreatePurchaseOrder(context.Context, *CreatePurchaseOrderRequest) (*PurchaseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePurchaseOrder not implemented")
}
func (UnimplementedProcurementServiceServer) GetPurchaseOrder(context.Context, *GetPurchaseOrderRequest) (*PurchaseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPurchaseOrder not implemented")
}
func (UnimplementedProcurementServiceServer) ListPurchaseOrders(context.Context, *ListPurchaseOrdersRequest) (*ListPurchaseOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPurchaseOrders not implemented")
}
func (UnimplementedProcurementServiceServer) mustEmbedUnimplementedProcurementServiceServer() {}
func (UnimplementedProcurementServiceServer) testEmbeddedByValue()                            {}

// UnsafeProcurementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcurementServiceServer will
// result in compilation errors.
type UnsafeProcurementServiceServer interface {
	mustEmbedUnimplementedProcurementServiceServer()
}

func RegisterProcurementServiceServer(s grpc.ServiceRegistrar, srv ProcurementServiceServer) {
	// If the following call pancis, it indicates UnimplementedProcurementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcurementService_ServiceDesc, srv)
}

func _ProcurementService_CreateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcurementServiceServer).CreateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcurementService_CreateSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcurementServiceServer).CreateSupplier(ctx, req.(*CreateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcurementService_ListSuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcurementServiceServer).ListSuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcurementService_ListSuppliers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcurementServiceServer).ListSuppliers(ctx, req.(*ListSuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcurementService_CreatePurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcurementServiceServer).CreatePurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcurementService_CreatePurchaseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcurementServiceServer).CreatePurchaseOrder(ctx, req.(*CreatePurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcurementService_GetPurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcurementServiceServer).GetPurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcurementService_GetPurchaseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcurementServiceServer).GetPurchaseOrder(ctx, req.(*GetPurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcurementService_ListPurchaseOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchaseOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcurementServiceServer).ListPurchaseOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcurementService_ListPurchaseOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcurementServiceServer).ListPurchaseOrders(ctx, req.(*ListPurchaseOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcurementService_ServiceDesc is the grpc.ServiceDesc for ProcurementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcurementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erp.procurement.v1.ProcurementService",
	HandlerType: (*ProcurementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSupplier",
			Handler:    _ProcurementService_CreateSupplier_Handler,
		},
		{
			MethodName: "ListSuppliers",
			Handler:    _ProcurementService_ListSuppliers_Handler,
		},
		{
			MethodName: "CreatePurchaseOrder",
			Handler:    _ProcurementService_CreatePurchaseOrder_Handler,
		},
		{
			MethodName: "GetPurchaseOrder",
			Handler:    _ProcurementService_GetPurchaseOrder_Handler,
		},
		{
			MethodName: "ListPurchaseOrders",
			Handler:    _ProcurementService_ListPurchaseOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "erp/procurement/v1/procurement.proto",
}
